### ISSUE TITLE
MacOS support?

### ISSUE THREAD

**Issue by apecoraro** [vikram25897/flutter_cached_video_player#5]
I tried to use this in a macOS Flutter app, but when it tried to run "pod install" the following error popped up:

```
$ pod install
Analyzing dependencies
[!] No podspec found for `cached_video_player` in `Flutter/ephemeral/.symlinks/plugins/cached_video_player/macos`
```

I have this in my pubspec.yaml:
```
environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_video_player: ^1.0.3
```

**Comment by vikram25897** [comment]
@apecoraro As this plugin builds on top of official `video_player` plugin, and because that one doesn't have MacOS, Windows or Linux support, so our plugin also doesn't have it. But we'll keep an eye out for that, and as soon as flutter adds `PlatformView` support for desktop environments, we'll add it.

**Comment by JayPerfetto** [comment]
I feel like Video Player supports MacOS now - could be time for a package update
