### ISSUE TITLE
audiomixing with other video

### ISSUE THREAD

**Issue by chinu999** [vikram25897/flutter_cached_video_player#7]
when i play a video works fine.But when i play a video in pageview and scroll down to other video it mix the audio with my upper video is their any focus methord.

**Comment by AbhayVAshokan** [comment]
> when i play a video works fine.But when i play a video in pageview and scroll down to other video it mix the audio with my upper video is their any focus methord.

I faced a similar issue with my project. I shall tell you how I solved it. 

First of all it is not the issue with ```flutter_cached_video_player``` plugin. The same issue persists even if you replace ```flutter_cached_video_player``` with normal ```video_player```.
Why? The video plays as long as the ```pause()``` method or the ```dispose()``` method is called. 
In ```PageView.builder()``` the ```dispose()``` method is called automatically only when the page is scrolled completely out of view. Hence the video pauses.

To answer your question, two videos will play simultaneously if you scroll ***midway between two pages***. As you suggested, the solution is to use some kind of focus on the ```video_player```. 
I used [visibility_detector](https://pub.dev/packages/visibility_detector) package to solve the issue. I wrapped my ```video_player``` with it. I gave the configuration to call ```pause()``` method if the ```video_player``` is not 100% visible else call ```play()``` method. 

It solved many other issues as well. Supposedly, the video is not disposed when you simply switch a tab in the ```BottomNavigationBar``` or ```push``` a new page on top of the existing page and all. This package solved all those bugs.

I hope this solved your issue. I am open to doubts or alternative suggestions.

**Comment by chinu999** [comment]
Thanks bro it works for me as well but it takes 1.2 sec to stop.is their any solution to dispose in 0 sec.I know i am asking a lot. But i  am just curious.

**Comment by AbhayVAshokan** [comment]
> Thanks bro it works for me as well but it takes 1.2 sec to stop.is their any solution to dispose in 0 sec.I know i am asking a lot. But i am just curious.

```visibility_detector``` package works as a listener. Checking the screen every millisecond is performance intensive. I approximated that it might be checking every second. In addition to this, the ```flutter_cached_video_player``` disposes asynchronously. So there is an additional fraction of a second delay added to the same.
I am not sure if it is possible to provide the refresh rate to the ```visibility_detector``` or there is an alternative package available which does the same. Either way, if it is possible, I would recommend to adjust to just half a second (atmost) so that it does not affect the application performance.

**Comment by vikram25897** [comment]
My project, for which I created this plugin had a tiktok style UI. In that case I wrapped the `ListView` with `NotificationListener` and I listened to `ScrollNotification`. In the main screen I maintained a field named `currentlyPlayingUrl`, and on the basis of notification, I calculated as to which video is currently playing. If the url obtained from that calculation is different from the currently set `currentlyPlayingUrl`, then I just call `setState` with new value of `currentlyPlayingUrl`. And you can pass `currentlyPlayingUrl` and `videoUrl` to the constructors of your video player widget, and when the value of `currentlyPlayingUrl` is updated, then `didUpdateWidget` is called, when I actually did the `pause` and `resume` by comparing my `videoUrl` to `currentlyPlayingUrl`. @AbhayVAshokan @chinu999 You guys can try if this approach suits your needs. I think this approach is better than the `visibility_detector` approach, because if you have a lot of `video_player` widgets then their `onVisibilityChanged` will be getting called at every frame. While in my approach, the whole list has a single `NotificationListener` that is calling `setState` only when you need to change something. And about navigation also, I can get all kinds of effects by manipulation the value of `currentlyPlayingUrl`, for example setting to null when the screen is changed, and again setting it to an actual URL on getting back to screen, pausing all videos during scroll, etc. In my case, the pause and resume happened almost instantaneously even though I had 50-60 videos in the feed.


Also closing this issue, as it is not actually related to this plugin.

**Comment by AbhayVAshokan** [comment]
Let's consider Tik Tok for instance. There are several elements in the feeds screen that can redirect you away from the video screen. Also there is a possibility where a ```video_player``` instance is open in a different tab in the ```BottomNavigationBar``` stack as well. So navigating back and forth between the various screens demands us to play the video whenever it is in focus and pause whenever it is not. I am not sure if the ```setState``` method is gonna work. 

I stumbled upon the ```visibility_detector``` package when I could not pause the video by calling ```setState``` in the first screen and at the same time play the video in the second screen (profile screen) when I tap the ```BottomNavigationBar```.

**Comment by vikram25897** [comment]
@AbhayVAshokan I am not sure if our requirements are similar, but I had two separate video feeds, switchable by tab controller at top. On bottom there is a `BottomNavigationBar`. I used `NotificationListener`, for scroll updates in each feed, `NavigatorObserver` for routes getting pushed or popped on top of my feed, `TabController` for switching betwen two feeds, and `onTap` of `BottopNavigationBar` for when the page is switched. I put the logic of rest 3 in a single `ChangeNotifier` to which my actual feed screens were listening. I know that it is a lot more trouble than just using `visibility_detector`, but it gave me more freedom, and better performance too.

**Comment by AbhayVAshokan** [comment]
Thank you @vikram25897. Your method seems more promising.

**Comment by vikram25897** [comment]
@AbhayVAshokan but in the end whatever works for you is the best solution.

**Comment by ErnestoPapeto** [comment]
> My project, for which I created this plugin had a tiktok style UI. In that case I wrapped the `ListView` with `NotificationListener` and I listened to `ScrollNotification`. In the main screen I maintained a field named `currentlyPlayingUrl`, and on the basis of notification, I calculated as to which video is currently playing. If the url obtained from that calculation is different from the currently set `currentlyPlayingUrl`, then I just call `setState` with new value of `currentlyPlayingUrl`. And you can pass `currentlyPlayingUrl` and `videoUrl` to the constructors of your video player widget, and when the value of `currentlyPlayingUrl` is updated, then `didUpdateWidget` is called, where I actually did the `pause` and `resume` by comparing my `videoUrl` to `currentlyPlayingUrl`. @AbhayVAshokan @chinu999 You guys can try if this approach suits your needs. I think this approach is better than the `visibility_detector` approach, because if you have a lot of `video_player` widgets then their `onVisibilityChanged` will be getting called at every frame. While in my approach, the whole list has a single `NotificationListener` that is calling `setState` only when you need to change something. And about navigation also, I can get all kinds of effects by manipulation the value of `currentlyPlayingUrl`, for example setting to null when the screen is changed, and again setting it to an actual URL on getting back to screen, pausing all videos during scroll, etc. In my case, the pause and resume happened almost instantaneously even though I had 50-60 videos in the feed.
> 
> Also closing this issue, as it is not actually related to this plugin.

Heya,

can you share a link for reference? or a tutorial? This is much needed.
